version: "3.8"

services: 
    db:
        image: mariadb:latest
        container_name: maria_pose
        environment:
            MARIADB_ROOT_PASSWORD: developer
            MARIADB_DATABASE: fruit
            MARIADB_USER: developer
            MARIADB_PASSWORD: developer
        ports:
            - 3306:3306
        networks:
            backend: 
                aliases: 
                    - db
    api:
        build:
            context: .
            dockerfile: ./src/main/docker/Dockerfile.jvm
        image: fruits:dev
        container_name: fruits-api-dev
        depends_on: 
            - db
        ports: 
            - 8080:8080
        networks: 
            - backend

networks:
    backend:
        name: network-backend
        driver: bridge
